### ISSUE TITLE
Logged Null check operator used on a null value

### ISSUE THREAD

**Issue by velten-dev** [machinescream/worker_manager#103]
I am occasionally seeing a platform exception. The exception is the following. The formatting is my own from my app. The error comes from having an error catcher on 
```dart
PlatformDispatcher.instance.onError
```
The logged error is:

```
PLATFORM EXCEPTION: 2024-09-15 12:14:47.355169

Null check operator used on a null value

STACKTRACE:

#0      WorkerImpl.initialize.<anonymous closure> (package:worker_manager/src/worker/worker_io.dart:44)
#1      _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184)


END EXCEPTION
```

As the error indicates, the error seems to be the not-null assertion in the initialize function for the class class WorkerImpl in worker_manager/src/worker/worker_io.dart

```dart
  @override
  Future<void> initialize() async {
    _sendPortReceived = Completer<void>();
    _receivePort = RawReceivePort();
    _receivePort.handler = (Object result) {
      if (result is SendPort) {
        _sendPort = result;
        _sendPortReceived!.complete();
      } else if (result is ResultSuccess) {
        _result!.complete(result.value);
        _cleanUp();
      } else if (result is ResultError) {
        _result!.completeError(result.error, result.stackTrace);
        _cleanUp();
      } else {
        onMessage?.call(result);
      }
    };
    _isolate = await Isolate.spawn(
      _anotherIsolate,
      _receivePort.sendPort,
      errorsAreFatal: false,
      paused: false,
    );
    await _sendPortReceived!.future;
  }
```

I suggest changing calls of ```_result!``` to ```_result?``` so that an error is not generated. Both the ```completeError``` and ```complete``` functions are void return type so we do not need the ```_result``` variable to be non-null.

**Comment by machinescream** [comment]
Hello, thanks for feedback.
Lets overview what is the lifecycle of task in worker_io.
1) Before any task runned in worker, scheduler initializes isolate with callbacks where result! is defined.
2) Any callbacks rather than port receiving unexpected to be called
3) After work method called, result is setting to non-nullable value, that means that result is ready to use in callbacks of initialization.
4) Only cleanUp could affect result variable, and it's called only after receiving something and passed to non-null result.

It's seems like kill method could be called for example also, but according to the nature of stack data structure used to execute functions during runtime it is impossible to get callback execution after setting result to null, because isolate killed already, synchronously and port is closed. The only problem could affect this behavior is some changes in new dart versions, can you replicate this behavior with older versions and prepare minimal example to replicate this bug and to write some tests on. Thanks!

**Comment by machinescream** [comment]
Closing for now, till example is not presented

**Comment by velten-dev** [comment]
Here is a simple reproducer of the issue. I see a null check operator used on a null value logged in the console. Tested in both Linux and Android. 

```dart
import 'dart:io';

import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:worker_manager/worker_manager.dart';

void main() async {
  await workerManager.init(isolatesCount: 1);

  FlutterError.onError = (final details) {
    FlutterError.presentError(details);
    print('Flutter');
    print(details.exception);
  };
  PlatformDispatcher.instance.onError = (final error, final stack) {
    print('Platform');
    print(error);
    print(stack);
    return true;
  };
  runApp(const ExampleApp());
}

class ExampleApp extends StatelessWidget {
  const ExampleApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: Scaffold(
        body: Center(
          child: TextButton(
              onPressed: () async {
                final cancelable =
                    workerManager.executeGentle((final isCancelled) {
                  while (!isCancelled()) {
                    print('Loop');
                    sleep(Durations.long4);
                    final bool check = isCancelled();
                    if (!check) return;
                    print('after check');
                  }
                });
                sleep(Durations.long1);
                cancelable.cancel();
                print('canceled');
              },
              child: const Text('Test Worker')),
        ),
      ),
    );
  }
}

```

**Comment by machinescream** [comment]
thank you for the example of the code, I will try to replicate this problem asap
